### ISSUE TITLE
Question: is it possible to preload 

### ISSUE THREAD

**Issue by PimVanLommel** [duyduong/flutter_native_admob#15]
Hi, thank you for your amazing work. I use your plugin in a ListView like your example, but is it possible to preload the ads for example in the initState or elsewhere?
I dont want my users to see the loading spinner.
Again, thank  you for your work.

**Comment by duyduong** [comment]
@PimVanLommel Next release will be out soon which allow u to use custon loading and error widget. Your suggestion should be one of the features

**Comment by PimVanLommel** [comment]
That sounds great, thank you for your response.
Can you give me a timeframe when we can expect the new release?

**Comment by duyduong** [comment]
I am working it now, maybe about 1 or 2 weeks

**Comment by duyduong** [comment]
@PimVanLommel I updated version 2.0.0. This is a major update with a lot of changes. In your case, check this example [Hide ad until completed](https://github.com/duyduong/flutter_native_admob#hide-the-ad-until-it-load-completed)

**Comment by mhassanist** [comment]
@duyduong I don't think this is was the requested feature. I believe what we need is someway to preload the ad then show it later at any widget; so that when we have ad in some screen we don't have to wait for it till it loads if, we see it immediately.

**Comment by vinayaksankeet99** [comment]
How about we just create a static widget in the main page with height 0. Then call the widget later on in any of the subpages to display the ad. Is it possible? and is it legal?
