### ISSUE TITLE
setOptions method not working

### ISSUE THREAD

**Issue by XSiyabonga** [duyduong/flutter_native_admob#16]
Native ad controller resets to default styles when changed using the oncreate method controller

**Comment by duyduong** [comment]
@XSiyabonga Please wait for next release which is better that allows u to use custon loading and error widget

**Comment by XSiyabonga** [comment]
> @XSiyabonga Please wait for next release which is better that allows u to use custom loading and error widget

Alright, do you know what might be the issue with the setOptions method. Just looks like the BannerOptions I have set aren't applied. This feature is critical in my app as I have theme changes and the ads aren't changing with. If you have any idea what might be causing that would be great to know, I will do a local change on my side

**Comment by duyduong** [comment]
@XSiyabonga No more waiting. The major update 2.0.0 is ready. Please check example for usages
