### ISSUE TITLE
[2.0.0] NativeAdmobOptions is not overriding theme

### ISSUE THREAD

**Issue by devibrahimkarahan** [duyduong/flutter_native_admob#17]
First of all, thanks for the package. Its really good.

I am using NativeAdmobOptions for change ad theme, but its not change anything.

My NativeAdmobOptions (show media works but styles not working)
```
NativeAdmob(
        adUnitID: "ca-app-pub-3940256099942544/2247696110", // Google native unit id for test
        options: NativeAdmobOptions(
          ratingColor: Colors.red,
          headlineTextStyle: NativeTextStyle(color: Colors.red),
          bodyTextStyle: NativeTextStyle(color: Colors.red),
        ),
      ),
```
Result:
![image](https://user-images.githubusercontent.com/7039967/76686330-a79e0780-662b-11ea-9425-3ed2a7e5eb66.png)

**Comment by duyduong** [comment]
@devibrahimkarahan Hey, thanks for pointing this out. Just reviewed the code and fixed the issue. Please update to the latest to get the fix!

Close this if that is not happening anymore

**Comment by devibrahimkarahan** [comment]
Thanks, fixed
