### ISSUE TITLE
I can't load banner

### ISSUE THREAD

**Issue by jesusgear2** [duyduong/flutter_native_admob#2]
First, congratulate on his work, I find this package very interesting.
I have one problem with NativeAdmobBannerView, i implement this in mi example api, and i can't load the banner , only i can see load circle.

I am use appID to test:

  final _nativeAdmob = NativeAdmob();
  _nativeAdmob.initialize(appID: 'ca-app-pub-3940256099942544~3347511713');

            NativeAdmobBannerView(
              adUnitID: 'ca-app-pub-3940256099942544/6300978111',
              style: BannerStyle.light, // enum dark or light
              showMedia: true, // whether to show media view or not
              contentPadding: EdgeInsets.fromLTRB(8.0, 8.0, 8.0, 0.0), // content padding
            )

Regards,

**Comment by duyduong** [comment]
Is it ur real ad unit ID? Can u try with test ad unit? I heard that Admob did not release native ads yet. If u want to use real native ads, u need to contact Admob for that

**Comment by jesusgear2** [comment]
Is test Unid ID, will look for the solution to the problem

**Comment by incafox** [comment]
same problema here

**Comment by duyduong** [comment]
Please search for console log `onAdFailedToLoad`. I actually printed the error code when the ad is failed to load

**Comment by AlexisThink** [comment]
I have the **error code 0** and in other times the **error code 2** but still apper the circle loading in both.

Whats mean, what can i do?

**Comment by duyduong** [comment]
Hi guys, I will actively fix/update the plugin. Also support for iOS, so please wait for next version. Thanks!

**Comment by duyduong** [comment]
Guys, New version 1.0.0 is released, can u try again? I also update details setup for both Android and iOS.

**Comment by duyduong** [comment]
Reopen if the issue still existed

**Comment by ysknsn** [comment]
I had the same problem in 1.0.0.

It happens on Android / iOS

When I build with Xcode, the log 
**"NativeAdmobBannerView: ad loaded failed with error: Request Error: No ad to show."**
 was displayed

I am using adUnitId which is displayed without any problem in firebase_admob and other admob plugins.
 
 
I am very grateful that there are not many admob plugins using platformview.
Thank you.

**Comment by duyduong** [comment]
@ysknsn maybe because u habe just creating the ad unit id. I think u will need to wait

**Comment by duyduong** [comment]
@ysknsn is the ad unit is native ad? Otherwise it won't work

**Comment by ymdarake** [comment]
Hi!

Thanks for your great work @duyduong !
I got the same problem here, and that was because I was using a wrong test ad id `ca-app-pub-3940256099942544/6300978111` instead of the correct one `ca-app-pub-3940256099942544/2247696110`.

The thing is that the type of ads here is `NativeAd`, not `Banner`, as we can find the detail there↓.
https://github.com/duyduong/flutter_native_admob/blob/master/android/src/main/kotlin/com/nover/flutternativeadmob/NativeAdmobBannerViewFactory.kt#L152

I hope this will help others facing the same error.
Thanks!

**Comment by ysknsn** [comment]
@duyduong 
Sorry i used the ad unit for banner. 
thanks.
