### ISSUE TITLE
Hide the ad until it load completed doesnt work !

### ISSUE THREAD

**Issue by mahadydev** [duyduong/flutter_native_admob#23]
Hello , Thanks for amazing work . My issue is , I can't get the "Hide the ad until it load completed" to work. I've tried everything ! I think the ` _subscription = _nativeAdController.stateChanged.listen(_onStateChanged);` line doesnt work because i tried to put a print('test') inside 
`case AdLoadState.loading:
        setState(() {
          _height = 0;
           //print('test');
        });` but it wont print anything to the console. also the height doesn't change .stays 0. if i change the height to 330 manually it shows the ad. What am I doing wrong? thanks

**Comment by duyduong** [comment]
@mahadydev Hey, just checked the example code, I forgot to assign controller to `NativeAdmob` widget. Please see below

```
NativeAdmob(
  // Your ad unit id
  adUnitID: _adUnitID,
  controller: _nativeAdController, <- add this

  // Don't show loading widget when in loading state
  loading: Container(),
),
```

**Comment by mahadydev** [comment]
hey thanks for fixing that ! works nice now
