### ISSUE TITLE
Memory Issue

### ISSUE THREAD

**Issue by yalcinozdemir** [duyduong/flutter_native_admob#25]
While testing on iOS, I found out that these ads consume so much memory. After listing 10-20 ads in the list view, it takes up to 1gb memory and eventually, the app crashes with error `"Message from debugger: Terminated due to memory issue".` Can you please check for memory leaks or possible fixes regarding this issue? 

Thank you for taking the time to maintain this package.

**Comment by tudorcodarnai** [comment]
Same here, Xcode screenshot attached after running around 20 ads. Proc 100%, memory around 700MB on an iPhone 6S (dev device). And the processor and memory are not being released.

<img width="273" alt="Screenshot 2020-03-22 at 20 38 41" src="https://user-images.githubusercontent.com/5359488/77257457-1f4be200-6c7d-11ea-8107-76c274dfa70a.png">

**Comment by duyduong** [comment]
@yalcinozdemir @tudorcodarnai Hey, I noticed that. Please update to latest version and try to dispose ad controller. U can also share ad controller between `NativeAdmob` widgets, don't need to create separated controller for each widget, this will save u a lot

**Comment by tudorcodarnai** [comment]
@duyduong if I'm using only one controller for both ad positions, the first ad does not react to taps on the screen, it loads but does nothing.

I also keep getting these messages in the iOS console, maybe it has something to do with that? I am confused, the log says "User interactions must be disabled on the asset view to enable click handling." and then "userInteractionEnabled has been set to NO". So... is this right or not? How can I fix it? 

2020-03-23 09:39:01.788815+0200 DCNews[6068:677779] <Google> User interactions must be disabled on the asset view to enable click handling.
userInteractionEnabled has been set to NO on <UIButton: 0x15bba06d0; frame = (0 0; 0 0); opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x282437980>>.
2020-03-23 09:39:01.789053+0200 DCNews[6068:677779] <Google> User interactions must be disabled on the asset view to enable click handling.
userInteractionEnabled has been set to NO on <flutter_native_admob.StackLayout: 0x15bb2e0e0; baseClass = UIStackView; frame = (0 0; 0 0); userInteractionEnabled = NO; layer = <CATransformLayer: 0x282437640>>.
2020-03-23 09:39:01.795398+0200 DCNews[6068:677779] <Google> User interactions must be disabled on the asset view to enable click handling.
userInteractionEnabled has been set to NO on <UIButton: 0x15bcaed60; frame = (0 0; 0 0); opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x282436500>>.
2020-03-23 09:39:01.795586+0200 DCNews[6068:677779] <Google> User interactions must be disabled on the asset view to enable click handling.
userInteractionEnabled has been set to NO on <flutter_native_admob.StackLayout: 0x15bca89a0; baseClass = UIStackView; frame = (0 0; 0 0); userInteractionEnabled = NO; layer = <CATransformLayer: 0x282436980>>.

**Comment by yalcinozdemir** [comment]
> @yalcinozdemir @tudorcodarnai Hey, I noticed that. Please update to latest version and try to dispose ad controller. U can also share ad controller between `NativeAdmob` widgets, don't need to create separated controller for each widget, this will save u a lot

Hey, I am using the latest version of the repo and only one ad controller as well as disposing of it. However, after displaying 10 ads, memory usage easily goes 1gb.

**Comment by duyduong** [comment]
@tudorcodarnai That is just a log from Google SDK, not an issue. But yeah, if u r using one controller, it will share the native ad data and the media as well. In your case, u need to use 2 controllers
@yalcinozdemir That's quite a lot of ads. As the ads contains video, I think it makes sense. Can u try to turn off video on Admob configuration and see

**Comment by a-leblond** [comment]
Hi,
Could it be related to https://github.com/flutter/flutter/issues/46666 as it uses Platform Views ?

**Comment by apple-creator** [comment]
> @duyduong if I'm using only one controller for both ad positions, the first ad does not react to taps on the screen, it loads but does nothing.
> 
> I also keep getting these messages in the iOS console, maybe it has something to do with that? I am confused, the log says "User interactions must be disabled on the asset view to enable click handling." and then "userInteractionEnabled has been set to NO". So... is this right or not? How can I fix it?
> 
> User interactions must be disabled on the asset view to enable click handling.
> userInteractionEnabled has been set to NO on <UIButton: 0x15bba06d0; frame = (0 0; 0 0); opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x282437980>>.
> 
> User interactions must be disabled on the asset view to enable click handling.
> userInteractionEnabled has been set to NO on <flutter_native_admob.StackLayout: 0x15bb2e0e0; baseClass = UIStackView; frame = (0 0; 0 0); userInteractionEnabled = NO; layer = <CATransformLayer: 0x282437640>>.
> 
> User interactions must be disabled on the asset view to enable click handling.
> userInteractionEnabled has been set to NO on <UIButton: 0x15bcaed60; frame = (0 0; 0 0); opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x282436500>>.
> 
> User interactions must be disabled on the asset view to enable click handling.
> userInteractionEnabled has been set to NO on <flutter_native_admob.StackLayout: 0x15bca89a0; baseClass = UIStackView; frame = (0 0; 0 0); userInteractionEnabled = NO; layer = <CATransformLayer: 0x282436980>>.

Did You manage to resolve it?
