### ISSUE TITLE
Can't add a test device

### ISSUE THREAD

**Issue by elliptic1** [duyduong/flutter_native_admob#26]
I can't find where to add a test device ID for fake ads.

**Comment by duyduong** [comment]
If u r running on simulator, it will fetch the test ad

**Comment by huzaifasaeed** [comment]
@duyduong Native Ads are not showing, this error shows up

Use RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("CCAA0E96D3E7FC32C838D8614AF9A61E") to get test ads on this device.
Ad failed to load : 3
onAdFailedToLoad errorCode = 3
