### ISSUE TITLE
NativeAdmob doesn't show properly in ListView

### ISSUE THREAD

**Issue by a-leblond** [duyduong/flutter_native_admob#27]
Hi,

I'm using your example to prevent the ad to reload in a ListView, on first load everythings fine, but when I scroll and come back to the ad it doesn't show properly. 

I'm using a NativeAdmobController like mentionned, tried to reloadAd() and different things without success.

I noticed this behavior on Android (didn't tried on iOS yet). Both emulator and real device.

![Capture1](https://user-images.githubusercontent.com/26484419/77674169-71497c00-6f8b-11ea-9586-02f9be009dcf.PNG)
![Capture2](https://user-images.githubusercontent.com/26484419/77674173-71e21280-6f8b-11ea-826f-c31a0fe47b5a.PNG)

**Comment by duyduong** [comment]
@a-leblond Same controller will share the native ad data. If your 2 ads are in different places, u can use the same controller. In your case, just create 2 controller for 2 ads

**Comment by a-leblond** [comment]
Thanks for your response and your time. 

Even when I use multiple controllers, when an ad is displayed I scroll down and then scroll up to see the ad again, it becomes a blank ad. Each ad from the ListView has its own controller, and even when I force a refresh with _adControllers[index].reloadAd(forceRefresh: true) it has no effect.

I don't understand what's going on, if I don't set any controller it works fine to reload the ad when I scroll.

ListView code: 

```
return RefreshIndicator(
              onRefresh: () {
                _feedBloc.add(RefreshPosts());
                return Future.value();
              },
              child: ListView.builder(
                physics: BouncingScrollPhysics(parent: AlwaysScrollableScrollPhysics()),
                controller: _scrollController,
                itemCount: state.posts.length + (state.hasReachedMax ? 0 : 1),
                itemBuilder: (context, index) {
                  if(index<state.posts.length) {
                    if(state.posts[index].author == "ad") {
                      return _ad(index);
                    } else {
                      return PostWidget(key: ObjectKey(state.posts[index]),post: state.posts[index]);
                    }
                  } else
                    return Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: Center(
                        child: CircularProgressIndicator(),
                      ),
                    );
                },
              ),
            );
```

Ads code: 

```
Widget _ad(int index) {
    if(!_adControllers.containsKey(index)) {
      _adControllers[index] = NativeAdmobController();
    } else {
      //_adControllers[index].reloadAd(forceRefresh: true);
    }
    return Container(
      height: 330,
      padding: EdgeInsets.all(8),
      child: NativeAdmob(
        adUnitID: _adId,
        controller: _adControllers[index],
        options: NativeAdmobOptions(
          headlineTextStyle: NativeTextStyle(
            fontSize: Theme.of(context).textTheme.body1.fontSize,
            color: Colors.white,
            backgroundColor: Colors.grey 
          ),
          storeTextStyle: NativeTextStyle(
            fontSize: Theme.of(context).textTheme.body1.fontSize,
            color: Colors.white,
            backgroundColor: Colors.grey 
          ),
          bodyTextStyle: NativeTextStyle(
            fontSize: Theme.of(context).textTheme.body1.fontSize,
            color: Colors.white,
            backgroundColor: Colors.grey 
          ),
          advertiserTextStyle: NativeTextStyle(
            fontSize: Theme.of(context).textTheme.body1.fontSize,
            color: Colors.white,
            backgroundColor: Colors.grey 
          ),
          adLabelTextStyle: NativeTextStyle(
            fontSize: Theme.of(context).textTheme.body1.fontSize,
            color: Colors.black87,
            backgroundColor: Colors.white 
          ),
          callToActionStyle: NativeTextStyle(
            fontSize: Theme.of(context).textTheme.body1.fontSize,
            color: Colors.black87,
            backgroundColor: Colors.white 
          ),
          ratingColor: Colors.yellow
        ),
      ),
    );
  }
```

**Comment by korchix** [comment]
i have the same issue in GridView on iOS using a real device.
if i don't use a Controller, the ads reloads everytime i scroll and it's fine. 
but if i use Controller (or different controllers) the ad looks exactly like @a-leblond mentioned in the thread

**Comment by duyduong** [comment]
@a-leblond @korchix
New version is released. There is small bug that made the ad controller to dispose when the ad view is disposed. 
There is also new `NativeAdmobType` that allows to show it as banner or full. Please check the example

**Comment by sjghose** [comment]
I was having he same exact issue with my Android production ids where a blank placeholder would show up. I just tested the 2.1.0 - here are my observations:
Android
1. Fixed the reported issue with the blank placeholder ad
2. In my case the same ad is repeated if I use controller: _nativeAdController, 
3. if I remove the controller different ads show up (as desired). I am using PageView.builder to display ads between pages.
4. In GridView same test ad is repeated if using the controller
5. GridView shows no test ads without the controller

Will test IOS next.

**Comment by a-leblond** [comment]
I tested on Android and like @sjghose said it fixed the issue for the blank ad. I'll try later on iOS.
I use one controller per ad in my ListView so I can dispose each ad when I need, and everything works fine.

Thanks for your work 👍

**Comment by sjghose** [comment]
Appreciate your efforts - this is very helpful. 
Just tested with IOS simulator - my observations

1. No ads show with Test Unit id (I'll have to recheck the IOS test id is any good - ca-app-pub-3940256099942544/4411468910. If I use the Prod AdUnitid test Ads are shown.
2. In Gridview no ads display using the controller. Without the controller the same ad is repeated within the same instance of the Grid. (I'm displaying ads every 10 or so items. I have different controllers for Grid and Page views)
3. Pageview works the same as Android except that it only works with the Prod AdUnitid.

**Comment by korchix** [comment]
@duyduong the new release 2.1.0 fixes the issue with the blank ad, thank you. i tested it on real iOS device (Iphone X) and Emulator (Iphone 11 pro max)

but when scrolling, the ads reload, despite using a controller . here is the code of my NativeAdWidget.

`class NativeAdWidget extends StatefulWidget {
  final bool bigAd;
  const NativeAdWidget({Key key, this.bigAd}) : super(key: key);

  @override
  _NativeAdWidgetState createState() => _NativeAdWidgetState();
}

class _NativeAdWidgetState extends State<NativeAdWidget> {
  final _controller = NativeAdmobController();

  @override
  Widget build(BuildContext context) {
    return Card(
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(8),
      ),
      elevation: 3,
      child: Padding(
        padding: const EdgeInsets.all(4.0),
        child: NativeAdmob(
          options: NativeAdmobOptions(
              showMediaContent: widget.bigAd ? true : false,
              bodyTextStyle: widget.bigAd
                  ? NativeTextStyle(fontSize: 12)
                  : NativeTextStyle(isVisible: false),
              callToActionStyle:
                  NativeTextStyle(backgroundColor: kPrimaryColor),
              adLabelTextStyle:
                  NativeTextStyle(backgroundColor: Colors.grey.shade300)),
          adUnitID: testNative, //TODO change Native AD ID
          controller: _controller,
          loading: Container(),
//          type: widget.bigAd ? NativeAdmobType.full : NativeAdmobType.banner,
        ),
      ),
    );
  }
}`

i have 3 Native Ads in StaggeredGridView.countBuilder() of the package [flutter_staggered_grid_view](https://pub.dev/packages/flutter_staggered_grid_view#-readme-tab-)

**Comment by duyduong** [comment]
@korchix you should put your controller somewhere that is not dispose, for example in the page that contains the GridView, not in the widget that contains `NativeAdmob`. The GridView/ListView will reload your widget, which mean your controller is disposed

**Comment by duyduong** [comment]
> Appreciate your efforts - this is very helpful.
> Just tested with IOS simulator - my observations
> 
> 1. No ads show with Test Unit id (I'll have to recheck the IOS test id is any good - ca-app-pub-3940256099942544/4411468910. If I use the Prod AdUnitid test Ads are shown.
> 2. In Gridview no ads display using the controller. Without the controller the same ad is repeated within the same instance of the Grid. (I'm displaying ads every 10 or so items. I have different controllers for Grid and Page views)
> 3. Pageview works the same as Android except that it only works with the Prod AdUnitid.
> 
> Tested with Production AdUnit in IOS Testflite (flutter build IOS) and tested on real IOS devices (Iphone 11)
> 
> 1. Blank space displayed in Pageview  instead of the ad - just the outline (no using a controller). This was showing Test ads using the Prod AdUnit when doing a Debug Build.
> 2. Gridview - no ads displayed with Prod AdUnit - empty Container() so no display issues other than ads are missing (using controller).

The plugin is not supported for test ad unit. It will fetch the test ad when running on simulator

**Comment by duyduong** [comment]
@sjghose Thanks for your testing. 
If your ad is not showing in GridView/ListView, please check my above comment.

The main function of ad controller is to cache and share the native ad. It also supports for reloading anytime we want. By using ad controller, we can control our ad refresh rate. Google may block our ad unit if it is refreshed too much.

**Comment by a-leblond** [comment]
@duyduong I tested on iOS in release mode and it works fine in a ListView with a controller for each ad. I always keep the last 2 ads displayed loaded and dispose the older ones.

However there are frames drops when I scroll. There's never more than one ad displayed at a time in my Listview. I'll try to keep only the last ad loaded to see if it's better. 

I have an iPhone 11 Pro Max, I don't know if the drops are worse on an older iPhone.

**Comment by korchix** [comment]
> @korchix you should put your controller somewhere that is persisted during scrolling, for example in the page that contains the GridView, and pass it down to your ad widget.
> The GridView/ListView will reload your widget, which mean your controller is disposed with your code

thank you for the hint, that has resolved the issue.

**Comment by duyduong** [comment]
@a-leblond Yes, `UiKitView` is still an experiment feature. Use as your own risk :)

**Comment by azhar294** [comment]
@korchix  how did you solve the ad reload issue in list view. 
@duyduong i tried to pass the controller from a singleton class and still the ad reload while scrolling listview
