### ISSUE TITLE
Undefined class NativeAdmobOptions

### ISSUE THREAD

**Issue by Errechydy** [duyduong/flutter_native_admob#29]
Thanks for this great plugin
I wanted to use `NativeAdmobOptions` as you explained in [this example](https://pub.dev/packages/flutter_native_admob#-readme-tab-) but i got this error : 

> Undefined class 'NativeAdmobOptions'.

I'm using last version 2.1.0

**Comment by korchix** [comment]
@Errechydy please share the code you'r using, to let the people help you.

**Comment by Errechydy** [comment]
@korchix  The error has nothing to do with the code, it says `Undefined class 'NativeAdmobOptions'.`, which mean no matter what code you use you will get that error. it's like the NativeAdmobOptions method doesn't exist in the plugin at all and you're trying to use it.

To reproduce the error  you can use the exact same example that exist in the github, copy past the example and add the `NativeAdmobOptions ` you will get the error, her is an example:

```
import 'package:flutter/material.dart';
import 'package:flutter_native_admob/flutter_native_admob.dart';
import 'package:flutter_native_admob/native_admob_controller.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  static const _adUnitID = "ca-app-pub-3940256099942544/8135179316";

  final _nativeAdController = NativeAdmobController();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Plugin example app'),
        ),
        body: 
            Container(
              height: 90,
              child: NativeAdmob(
                adUnitID: _adUnitID,
                controller: _nativeAdController,
                type: NativeAdmobType.banner,
                options: NativeAdmobOptions(
                  ratingColor: Colors.red,
                ),
              ),
            )
        ),
    );
  }
} 
```

If you comment the `NativeAdmobOptions` the code will work

**Comment by korchix** [comment]
@Errechydy i see. you have to import the `native_admob_options.dart` too

`import 'package:flutter_native_admob/native_admob_options.dart';`

**Comment by Errechydy** [comment]
@korchix Thanks
