### ISSUE TITLE
Native Ad breaks layout in a list view in iOS

### ISSUE THREAD

**Issue by itielMaimon** [duyduong/flutter_native_admob#31]
Hi,

I'm loading a Native Ad in a list view inside a view pager, when the ad is loading everything seems to work fine, but after the ad is loaded it creates some weird behavior.
A Banner ad (which is an overlay, from 'firebase_admob') becomes hidden below the layout and scrolling isn't working properly.

What can I do to fix this?

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-05 at 06 57 03](https://user-images.githubusercontent.com/19761142/78500593-030d7200-7760-11ea-95a1-1bfa029e5db0.png)

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-05 at 07 05 14](https://user-images.githubusercontent.com/19761142/78500598-07398f80-7760-11ea-913d-7de26a94fd40.png)

**Comment by Klabauterman** [comment]
Same here!

**Comment by ChoiJun29** [comment]
same here

**Comment by itielMaimon** [comment]
Flutter recently announced official support of native and banner ads as part of the widget tree.

It's currently in public Beta but from testing it I can confirm it works great.

https://pub.dev/packages/google_mobile_ads
