### ISSUE TITLE
 Native Ads not showing on Test Device

### ISSUE THREAD

**Issue by huzaifasaeed** [duyduong/flutter_native_admob#35]
This error occue:

Use RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("CCAA0E96D3E7FC32C838D8614AF9A61E") to get test ads on this device.
Ad failed to load : 3
onAdFailedToLoad errorCode = 3

**Comment by M1Joe** [comment]
@huzaifasaeed maybe this will help you: https://github.com/duyduong/flutter_native_admob/issues/39
