### ISSUE TITLE
Ads in Listview.builder are reloading while scrolling the list up and down

### ISSUE THREAD

**Issue by hkndzdr** [duyduong/flutter_native_admob#38]
Ads  in Listview.builder are reloading while scrolling the list up and down.  I used ads() method in a listview.builder with a controller.

Sample code
```
 final _nativeAdMobController = NativeAdmobController();
 StreamSubscription _nativeAdMobSubscription;
 double _height = 0;

@override
  void initState() {
   _nativeAdMobSubscription = _nativeAdMobController.stateChanged.listen(_onStateChanged);
    super.initState();
  }

@override
  void dispose() {
    _nativeAdMobSubscription.cancel();
   _nativeAdMobController.dispose();
    super.dispose();
  }

ads () {
    return NativeAdmob(
      adUnitID: getBannerAdUnitId(),
      loading: Container(),
     controller: _nativeAdMobController,
      type: NativeAdmobType.banner,
      options: NativeAdmobOptions(
          adLabelTextStyle: NativeTextStyle(isVisible: false),
      ),
    );
  }

  void _onStateChanged(AdLoadState state) {
    switch (state) {
      case AdLoadState.loading:
        setState(() {
          _height = 0;
        });
        break;

      case AdLoadState.loadCompleted:
        setState(() {
          _height = 80;
        });
        break;
      default:
        break;
    }
  }
```

**Comment by azhar294** [comment]
@hkndzdr how did you solve this issue

**Comment by hkndzdr** [comment]
> @hkndzdr how did you solve this issue
This problem occurs if the controller is defined within the ads class you customized. The controller must come from a parent widget as a parameter.

**Comment by azhar294** [comment]
> > @hkndzdr how did you solve this issue
> > This problem occurs if the controller is defined within the ads class you customized. The controller must come from a parent widget as a parameter.
Thanks @hkndzdr .

I have multiple ads in listview. So is i need seperate controller for each ad to load different ads?

**Comment by hkndzdr** [comment]
> > > @hkndzdr how did you solve this issue
> > > This problem occurs if the controller is defined within the ads class you customized. The controller must come from a parent widget as a parameter.
> > > Thanks @hkndzdr .
> 
> I have multiple ads in listview. So is i need seperate controller for each ad to load different ads?

Yes, but I don't think it's useful on the list. Because when the list is scrolled up and down, it loses its smoothness due to the reload of the ads.

**Comment by azhar294** [comment]
> > > > @hkndzdr how did you solve this issue
> > > > This problem occurs if the controller is defined within the ads class you customized. The controller must come from a parent widget as a parameter.
> > > > Thanks @hkndzdr .
> > 
> > 
> > I have multiple ads in listview. So is i need seperate controller for each ad to load different ads?
> 
> Yes, but I don't think it's useful on the list. Because when the list is scrolled up and down, it loses its smoothness due to the reload of the ads.

@hkndzdr I tried with one controller for multiple ad in infinite list view(data from api based on pagination) and the scroll freezing. Is any way to solve this. Thanks

**Comment by hkndzdr** [comment]
@azhar294 
No known method. Loading the controllers beforehand and keeping them ready may be the solution.
