### ISSUE TITLE
Can i Use Both firebase_admob &  flutter_native_admob ? Does this plugin  overide the firebase_admob interstitial ads settings 

### ISSUE THREAD

**Issue by spremathilaka** [duyduong/flutter_native_admob#50]
I was using firebase_admob 0.9.3+2 flutter plugin to show banner ads and interstitial ads  **(i have set Frequency capping for interstitial ads),**

I got a new requirement to show ads in between every 20 Liste Item, so I start using this plugin to implement this requirement "flutter_native_admob 2.1.0", 

Issue: I was able to display native banner ads as per the requirement, **but now all my interstitial ads showing full-screen Native kind Ads (Mostly Game Install ads)  and not follow the set  "Frequency capping",**   does that mean I can't use both plugs together?  Does this plugin override the interstitial ads settings ?

**Comment by duyduong** [comment]
@spremathilaka I nerver test that, as I mentioned use as ur own risk. I used in my current application and nothing happened
