### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by sabdelhay** [duyduong/flutter_native_admob#6]
I have followed your example, but I got this this unhandled exception:

> E/flutter (14990): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel flutter_native_admob)
> E/flutter (14990): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
> E/flutter (14990): <asynchronous suspension>
> E/flutter (14990): #1      NativeAdmob.initialize (package:flutter_native_admob/flutter_native_admob.dart:86:20)
> E/flutter (14990): <asynchronous suspension>

I would appreciate if you provide a solution for this exception. 
Thank you

**Comment by cimplesid** [comment]
initialize in the initstate 
`  final _nativeAd = NativeAdmob();`
```
void initState() {
    super.initState();
  
    _nativeAd.initialize(appID: "ca-app-pub-7341745842244329~9381057692");
   
}
```
then only implement

**Comment by duyduong** [comment]
@sabdelhay @cimplesid New version 1.0.0 is released, can u try again? I also update details setup for both Android and iOS. The `initialize` method has removed, please follow the details setup for both Android and iOS to let it work
