### ISSUE TITLE
[Question] NativeAdMob click to open advertisement

### ISSUE THREAD

**Issue by Cubel89** [duyduong/flutter_native_admob#64]
Good afternoon,

I am using this widget to put in a ListView and I have managed to configure everything without any problem, but I am realizing that no matter how much I click on the ad, it never opens.

How could I implement the onClick to open the destination url of the ad?

**Comment by haresh4d** [comment]
Same problem here. Can you share how you have configured to show ad on list view? I am using horizontal list view and on each page I want to show the ad.
