### ISSUE TITLE
Admob limited my account

### ISSUE THREAD

**Issue by zjamshidi** [duyduong/flutter_native_admob#89]
Does anybody experience ad limiting in Admob console after adding this library?

**Comment by ramtinq** [comment]
Did the limitation get fixed? I was planing to migrate using this plugin but after I read your case, I should double check if it is safe to use it.

**Comment by zjamshidi** [comment]
When I integrated this plugin into my app, my AdMob account got limited. So I'm not using it anymore. I suggest you investigate it more to avoid any income loss.

**Comment by ramtinq** [comment]
Ok, thanks for the suggestion.

**Comment by ramtinq** [comment]
Did you find a workaround? I see people reporting a similar problem in the official library provided by google team!
Here's the issue report:
https://github.com/googleads/googleads-mobile-flutter/issues/155

**Comment by zjamshidi** [comment]
I'm using [Firebase Admob](https://pub.dev/packages/firebase_admob) and it works fine. I know it's deprecated and I should migrate to [Google Mobile Ads SDK](https://pub.dev/packages/google_mobile_ads) soon.

What I understand is if you request several ads but only show a few of them, AdMob will limit your account.

**Comment by ramtinq** [comment]
Thanks for the information. Do you have any idea about if using AdMob's ads in a stack will cause it to be considered as fraud? Like an Stack of Positioned widgets which some of them (not necessarily the top one) contain Banner/Native ads.

**Comment by vishalknishad** [comment]
For me both of these (flutter_native_admob, firebase_admob) cause limited ad serving issue. Let's hope for the new ad package will be good.

**Comment by zjamshidi** [comment]
> Thanks for the information. Do you have any idea about if using AdMob's ads in a stack will cause it to be considered as fraud? Like a Stack of Positioned widgets which some of them (not necessarily the top one) contain Banner/Native ads.

@ramtinq There are specific policies applied to ads and Admob is very sensitive. Check this video for [Banner Ad](https://youtu.be/yTnqcz6RJ-4), you could find similar videos for other ad types. If a banner ad covers other UI elements or if it's too close to other UI elements, you are violating policies.

> For me both of these (flutter_native_admob, firebase_admob) cause limited ad serving issue. Let's hope the new ad package will be good.

@vishalknishad There might be something wrong with your implementation. The first time I implemented Interstitial Ads using firebase_admob my account got limited. I was loading Ads in init_state but showing ads every three screen views or so!  When I changed it, my accounts came live back.

**Comment by FernandoUFS** [comment]
> Does anybody experience ad limiting in Admob console after adding this library?

I had the same problem, I was migrating an app with a lot of users from native android to flutter, and few weeks later I had my account limited. I don't know what I am doing wrong, but I've already seen visual bugs on my ads using this library, like description text cut. Even if I use the full width and a lot space in height.

**Comment by yyyy-ltd** [comment]
@FernandoUFS I also have same problem. the developers here just deny it and ignore it. have you seen Chernobyl episode already?

**Comment by zjamshidi** [comment]
I suggest everybody use the official library o [Google Mobile Ads SDK](https://pub.dev/packages/google_mobile_ads)
