### ISSUE TITLE
Flutter Requires Kotlin Version 1.3.0

### ISSUE THREAD

**Issue by rajeshjeshar** [duyduong/flutter_native_admob#9]
`The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher. The following dependencies do not satisfy the required version: project ':flutter_native_admob' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71`

**Comment by nmnclk** [comment]
same issues.

**Comment by duyduong** [comment]
@rajeshjeshar @nmnclk New version 1.0.0 is released, can u try again? I also update details setup for both Android and iOS.

**Comment by rajeshjeshar** [comment]
@duyduong  Yes worked well,but why im unable to choose Text colors,styles and more customization unlike Native android devs do..
Can we expect any update from you?

**Comment by duyduong** [comment]
For now, I try to support general style so there are 2 styles only: `light` or `dark`

**Comment by rajeshjeshar** [comment]
@duyduong  [native ads](https://pub.dev/packages/native_ads) plugins supports custom layout method,but the problem is it shows blank on Release mode.This plugins works well on both builds without custom layout choosing option
